// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes list of buckets and their objects to be transformed.
public struct BucketList: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. List of buckets and their objects to be transformed. Currently,
  /// only one bucket configuration is supported. If multiple buckets are
  /// specified, an error will be returned.
  public var buckets: [BucketList.Bucket] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BucketList`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BucketList().with { $0.buckets = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let buckets = CodingKeys(stringValue: "buckets")

    static let _knownKeys: Set<Swift.String> = [
      "buckets"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([BucketList.Bucket].self, forKey: .buckets) {
      self.buckets = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.buckets, forKey: .buckets)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes configuration of a single bucket and its objects to be
  /// transformed.
  public struct Bucket: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Bucket name for the objects to be transformed.
    public var bucket: Swift.String = Swift.String()

    /// Specifies objects to be transformed.
    public var objectConfiguration: ObjectConfigurationOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Bucket`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Bucket().with { $0.bucket = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let bucket = CodingKeys(stringValue: "bucket")
      static let prefixList = CodingKeys(stringValue: "prefixList")
      static let manifest = CodingKeys(stringValue: "manifest")

      static let _knownKeys: Set<Swift.String> = [
        "bucket",
        "prefixList",
        "manifest",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .bucket) {
        self.bucket = value
      }

      var objectConfiguration: ObjectConfigurationOneOf? = nil
      let objectConfigurationCheckAndSet = {
        if objectConfiguration != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'objectConfiguration'"))
        }
        objectConfiguration = $0
      }
      if let prefixList = try container.decodeIfPresent(PrefixList?.self, forKey: .prefixList) {
        try objectConfigurationCheckAndSet(.prefixList(prefixList))
      }
      if let manifest = try container.decodeIfPresent(Manifest?.self, forKey: .manifest) {
        try objectConfigurationCheckAndSet(.manifest(manifest))
      }
      self.objectConfiguration = objectConfiguration
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.bucket, forKey: .bucket)

      if let choice = self.objectConfiguration {
        switch choice {
        case .prefixList(let value):
          try container.encode(value, forKey: .prefixList)
        case .manifest(let value):
          try container.encode(value, forKey: .manifest)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Specifies objects to be transformed.
    public enum ObjectConfigurationOneOf: Codable, Equatable, Sendable {
      /// Specifies objects matching a prefix set.
      indirect case prefixList(PrefixList?)
      /// Specifies objects in a manifest file.
      indirect case manifest(Manifest?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.storagebatchoperations.v1.BucketList.Bucket"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.BucketList"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
