// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes details about the progress of the job.
public struct Counters: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Number of objects listed.
  public var totalObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. Number of objects completed.
  public var succeededObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. The number of objects that failed due to user errors or
  /// service errors.
  public var failedObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. Number of bytes found from source. This field is only
  /// populated for jobs with a prefix list object configuration.
  public var totalBytesFound: Swift.Int64? = nil

  /// Output only. Number of object custom contexts created. This field is only
  /// populated for jobs with the UpdateObjectCustomContext transformation.
  public var objectCustomContextsCreated: Swift.Int64? = nil

  /// Output only. Number of object custom contexts deleted. This field is only
  /// populated for jobs with the UpdateObjectCustomContext transformation.
  public var objectCustomContextsDeleted: Swift.Int64? = nil

  /// Output only. Number of object custom contexts updated. This counter tracks
  /// custom contexts where the key already existed, but the payload was
  /// modified. This field is only populated for jobs with the
  /// UpdateObjectCustomContext transformation.
  public var objectCustomContextsUpdated: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Counters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Counters().with { $0.totalObjectCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let totalObjectCount = CodingKeys(stringValue: "totalObjectCount")
    static let succeededObjectCount = CodingKeys(stringValue: "succeededObjectCount")
    static let failedObjectCount = CodingKeys(stringValue: "failedObjectCount")
    static let totalBytesFound = CodingKeys(stringValue: "totalBytesFound")
    static let objectCustomContextsCreated = CodingKeys(stringValue: "objectCustomContextsCreated")
    static let objectCustomContextsDeleted = CodingKeys(stringValue: "objectCustomContextsDeleted")
    static let objectCustomContextsUpdated = CodingKeys(stringValue: "objectCustomContextsUpdated")

    static let _knownKeys: Set<Swift.String> = [
      "totalObjectCount",
      "succeededObjectCount",
      "failedObjectCount",
      "totalBytesFound",
      "objectCustomContextsCreated",
      "objectCustomContextsDeleted",
      "objectCustomContextsUpdated",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalObjectCount) {
      self.totalObjectCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .succeededObjectCount) {
      self.succeededObjectCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .failedObjectCount) {
      self.failedObjectCount = value
    }
    self.totalBytesFound = try container.decodeIfPresent(Swift.Int64.self, forKey: .totalBytesFound)
    self.objectCustomContextsCreated = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .objectCustomContextsCreated)
    self.objectCustomContextsDeleted = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .objectCustomContextsDeleted)
    self.objectCustomContextsUpdated = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .objectCustomContextsUpdated)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.totalObjectCount, forKey: .totalObjectCount)
    try container.encode(self.succeededObjectCount, forKey: .succeededObjectCount)
    try container.encode(self.failedObjectCount, forKey: .failedObjectCount)
    try container.encodeIfPresent(self.totalBytesFound, forKey: .totalBytesFound)
    try container.encodeIfPresent(
      self.objectCustomContextsCreated, forKey: .objectCustomContextsCreated)
    try container.encodeIfPresent(
      self.objectCustomContextsDeleted, forKey: .objectCustomContextsDeleted)
    try container.encodeIfPresent(
      self.objectCustomContextsUpdated, forKey: .objectCustomContextsUpdated)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.Counters"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
