// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A summary of errors by error code, plus a count and sample error log
/// entries.
public struct ErrorSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The canonical error code.
  public var errorCode: GoogleRpc.Code = GoogleRpc.Code()

  /// Required. Number of errors encountered per `error_code`.
  public var errorCount: Swift.Int64 = Swift.Int64()

  /// Required. Sample error logs.
  public var errorLogEntries: [ErrorLogEntry] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ErrorSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ErrorSummary().with { $0.errorCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let errorCode = CodingKeys(stringValue: "errorCode")
    static let errorCount = CodingKeys(stringValue: "errorCount")
    static let errorLogEntries = CodingKeys(stringValue: "errorLogEntries")

    static let _knownKeys: Set<Swift.String> = [
      "errorCode",
      "errorCount",
      "errorLogEntries",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(GoogleRpc.Code.self, forKey: .errorCode) {
      self.errorCode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .errorCount) {
      self.errorCount = value
    }
    if let value = try container.decodeIfPresent([ErrorLogEntry].self, forKey: .errorLogEntries) {
      self.errorLogEntries = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.errorCode, forKey: .errorCode)
    try container.encode(self.errorCount, forKey: .errorCount)
    try container.encode(self.errorLogEntries, forKey: .errorLogEntries)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.ErrorSummary"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
