// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes options for object metadata update.
public struct PutMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Updates objects Content-Disposition fixed metadata. Unset values
  /// will be ignored. Set empty values to clear the metadata. Refer
  /// https://cloud.google.com/storage/docs/metadata#content-disposition for
  /// additional documentation.
  public var contentDisposition: Swift.String? = nil

  /// Optional. Updates objects Content-Encoding fixed metadata. Unset values
  /// will be ignored. Set empty values to clear the metadata. Refer to
  /// documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-encoding.
  public var contentEncoding: Swift.String? = nil

  /// Optional. Updates objects Content-Language fixed metadata. Refer to ISO
  /// 639-1 language codes for typical values of this metadata. Max length 100
  /// characters. Unset values will be ignored. Set empty values to clear the
  /// metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-language.
  public var contentLanguage: Swift.String? = nil

  /// Optional. Updates objects Content-Type fixed metadata. Unset values will be
  /// ignored. Set empty values to clear the metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-type
  public var contentType: Swift.String? = nil

  /// Optional. Updates objects Cache-Control fixed metadata. Unset values will
  /// be ignored. Set empty values to clear the metadata. Additionally, the value
  /// for Custom-Time cannot decrease. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#caching_data.
  public var cacheControl: Swift.String? = nil

  /// Optional. Updates objects Custom-Time fixed metadata. Unset values will be
  /// ignored. Set empty values to clear the metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#custom-time.
  public var customTime: Swift.String? = nil

  /// Optional. Updates objects custom metadata. Adds or sets individual custom
  /// metadata key value pairs on objects. Keys that are set with empty custom
  /// metadata values will have its value cleared. Existing custom metadata not
  /// specified with this flag is not changed. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#custom-metadata
  public var customMetadata: [Swift.String: Swift.String] = [:]

  /// Optional. Updates objects retention lock configuration. Unset values will
  /// be ignored. Set empty values to clear the retention for the object with
  /// existing `Unlocked` retention mode. Object with existing `Locked` retention
  /// mode cannot be cleared or reduce retain_until_time. Refer to documentation
  /// in https://cloud.google.com/storage/docs/object-lock
  public var objectRetention: ObjectRetention? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PutMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PutMetadata().with { $0.contentDisposition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let contentDisposition = CodingKeys(stringValue: "contentDisposition")
    static let contentEncoding = CodingKeys(stringValue: "contentEncoding")
    static let contentLanguage = CodingKeys(stringValue: "contentLanguage")
    static let contentType = CodingKeys(stringValue: "contentType")
    static let cacheControl = CodingKeys(stringValue: "cacheControl")
    static let customTime = CodingKeys(stringValue: "customTime")
    static let customMetadata = CodingKeys(stringValue: "customMetadata")
    static let objectRetention = CodingKeys(stringValue: "objectRetention")

    static let _knownKeys: Set<Swift.String> = [
      "contentDisposition",
      "contentEncoding",
      "contentLanguage",
      "contentType",
      "cacheControl",
      "customTime",
      "customMetadata",
      "objectRetention",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.contentDisposition = try container.decodeIfPresent(
      Swift.String.self, forKey: .contentDisposition)
    self.contentEncoding = try container.decodeIfPresent(
      Swift.String.self, forKey: .contentEncoding)
    self.contentLanguage = try container.decodeIfPresent(
      Swift.String.self, forKey: .contentLanguage)
    self.contentType = try container.decodeIfPresent(Swift.String.self, forKey: .contentType)
    self.cacheControl = try container.decodeIfPresent(Swift.String.self, forKey: .cacheControl)
    self.customTime = try container.decodeIfPresent(Swift.String.self, forKey: .customTime)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .customMetadata)
    {
      self.customMetadata = value
    }
    self.objectRetention = try container.decodeIfPresent(
      ObjectRetention.self, forKey: .objectRetention)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.contentDisposition, forKey: .contentDisposition)
    try container.encodeIfPresent(self.contentEncoding, forKey: .contentEncoding)
    try container.encodeIfPresent(self.contentLanguage, forKey: .contentLanguage)
    try container.encodeIfPresent(self.contentType, forKey: .contentType)
    try container.encodeIfPresent(self.cacheControl, forKey: .cacheControl)
    try container.encodeIfPresent(self.customTime, forKey: .customTime)
    try container.encode(self.customMetadata, forKey: .customMetadata)
    try container.encodeIfPresent(self.objectRetention, forKey: .objectRetention)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.PutMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
