// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Storage Batch Operations offers a managed experience to perform batch
/// operations on millions of Cloud Storage objects in a serverless fashion. With
/// this service, you can automate and simplify large scale API operations
/// performed on Cloud Storage objects.
///
/// @Snippet(path: "StorageBatchOperationsQuickstart")
public final class StorageBatchOperationsClient: Clients.StorageBatchOperationsProtocol, Sendable {
  let inner: any Clients.StorageBatchOperationsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `StorageBatchOperationsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.StorageBatchOperationsStub = try Clients.StorageBatchOperationsTransport(
      options)
    inner = Clients.StorageBatchOperationsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.StorageBatchOperationsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Jobs in a given project.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// Gets a batch job.
  ///
  /// @Snippet(path: "StorageBatchOperations_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Creates a batch job.
  ///
  /// @Snippet(path: "StorageBatchOperations_CreateJob")
  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createJob(request: request, options: options)
  }

  /// Creates a batch job.
  ///
  /// @Snippet(path: "StorageBatchOperations_CreateJob")
  public func createJobPollingUntilDone(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Job> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Job>.State in
      return try op._extractStatus(Job.self)
    }
    let rawOp = try await self.createJob(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Job>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a batch job.
  ///
  /// @Snippet(path: "StorageBatchOperations_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Cancels a batch job.
  ///
  /// @Snippet(path: "StorageBatchOperations_CancelJob")
  public func cancelJob(
    request: CancelJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.CancelJobResponse {
    try await self.inner.cancelJob(request: request, options: options)
  }

  /// Lists BucketOperations in a given project and job.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListBucketOperations")
  public func listBucketOperations(
    request: ListBucketOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.ListBucketOperationsResponse {
    try await self.inner.listBucketOperations(request: request, options: options)
  }

  /// Gets a BucketOperation.
  ///
  /// @Snippet(path: "StorageBatchOperations_GetBucketOperation")
  public func getBucketOperation(
    request: GetBucketOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.BucketOperation {
    try await self.inner.getBucketOperation(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "StorageBatchOperations_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageBatchOperations_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageBatchOperations_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageBatchOperations_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageBatchOperations_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `StorageBatchOperationsClient`.
  ///
  /// To mock `StorageBatchOperationsClient` change your functions to receive
  /// `some StorageBatchOperationsProtocol` or `any StorageBatchOperationsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol StorageBatchOperationsProtocol: Sendable {
    /// See `StorageBatchOperationsClient.createJob`.
    func createJobPollingUntilDone(request: CreateJobRequest) async throws -> any GoogleGax
      .PollableOperation<Job>

    /// See `StorageBatchOperationsClient.createJob`.
    func createJobPollingUntilDone(
      parent: Swift.String,
      job: Job?,
      jobId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Job>

    /// See `StorageBatchOperationsClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageBatchOperationsV1.ListJobsResponse

    /// See `StorageBatchOperationsClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageBatchOperationsV1.Job

    /// See `StorageBatchOperationsClient.createJob`.
    func createJob(
      request: CreateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `StorageBatchOperationsClient.createJob`.
    func createJobPollingUntilDone(
      request: CreateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Job>

    /// See `StorageBatchOperationsClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageBatchOperationsClient.cancelJob`.
    func cancelJob(
      request: CancelJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageBatchOperationsV1.CancelJobResponse

    /// See `StorageBatchOperationsClient.listBucketOperations`.
    func listBucketOperations(
      request: ListBucketOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageBatchOperationsV1.ListBucketOperationsResponse

    /// See `StorageBatchOperationsClient.getBucketOperation`.
    func getBucketOperation(
      request: GetBucketOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudStorageBatchOperationsV1.BucketOperation

    /// See `StorageBatchOperationsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `StorageBatchOperationsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `StorageBatchOperationsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `StorageBatchOperationsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `StorageBatchOperationsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.StorageBatchOperationsProtocol {
  public func listJobs(request: ListJobsRequest) async throws
    -> GoogleCloudStorageBatchOperationsV1.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.ListJobsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listJobs(
    byItem: ListJobsRequest
  ) -> any AsyncSequence<Job, Swift.Error> {
    self.listJobs(byItem: byItem, options: .init())
  }

  /// Lists Jobs in a given project.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListJobs")
  public func listJobs(
    byItem: ListJobsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudStorageBatchOperationsV1.ListJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobs(
    parent: Swift.String,
  ) -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.parent = parent
    }
    return self.listJobs(byItem: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudStorageBatchOperationsV1.Job
  {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getJob(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageBatchOperationsV1.Job {
    let request = GetJobRequest().with {
      $0.name = name
    }
    return try await self.getJob(request: request)
  }

  public func createJob(request: CreateJobRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createJob(request: request, options: .init())
  }

  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createJobPollingUntilDone(request: CreateJobRequest) async throws -> any GoogleGax
    .PollableOperation<Job>
  {
    try await self.createJobPollingUntilDone(request: request, options: .init())
  }

  public func createJobPollingUntilDone(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Job> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Job>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createJobPollingUntilDone(
    parent: Swift.String,
    job: Job?,
    jobId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Job> {
    let request = CreateJobRequest().with {
      $0.parent = parent
      $0.job = job
      $0.jobId = jobId
    }
    return try await self.createJobPollingUntilDone(request: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteJob(
    name: Swift.String,
  ) async throws {
    let request = DeleteJobRequest().with {
      $0.name = name
    }
    try await self.deleteJob(request: request)
  }

  public func cancelJob(request: CancelJobRequest) async throws
    -> GoogleCloudStorageBatchOperationsV1.CancelJobResponse
  {
    try await self.cancelJob(request: request, options: .init())
  }

  public func cancelJob(
    request: CancelJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.CancelJobResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelJob(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageBatchOperationsV1.CancelJobResponse {
    let request = CancelJobRequest().with {
      $0.name = name
    }
    return try await self.cancelJob(request: request)
  }

  public func listBucketOperations(request: ListBucketOperationsRequest) async throws
    -> GoogleCloudStorageBatchOperationsV1.ListBucketOperationsResponse
  {
    try await self.listBucketOperations(request: request, options: .init())
  }

  public func listBucketOperations(
    request: ListBucketOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.ListBucketOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBucketOperations(
    byItem: ListBucketOperationsRequest
  ) -> any AsyncSequence<BucketOperation, Swift.Error> {
    self.listBucketOperations(byItem: byItem, options: .init())
  }

  /// Lists BucketOperations in a given project and job.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListBucketOperations")
  public func listBucketOperations(
    byItem: ListBucketOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<BucketOperation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudStorageBatchOperationsV1.ListBucketOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBucketOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBucketOperations(
    parent: Swift.String,
  ) -> any AsyncSequence<BucketOperation, Swift.Error> {
    let request = ListBucketOperationsRequest().with {
      $0.parent = parent
    }
    return self.listBucketOperations(byItem: request)
  }

  public func getBucketOperation(request: GetBucketOperationRequest) async throws
    -> GoogleCloudStorageBatchOperationsV1.BucketOperation
  {
    try await self.getBucketOperation(request: request, options: .init())
  }

  public func getBucketOperation(
    request: GetBucketOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudStorageBatchOperationsV1.BucketOperation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBucketOperation(
    name: Swift.String,
  ) async throws -> GoogleCloudStorageBatchOperationsV1.BucketOperation {
    let request = GetBucketOperationRequest().with {
      $0.name = name
    }
    return try await self.getBucketOperation(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocations(byItem: byItem, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "StorageBatchOperations_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "StorageBatchOperations_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
